[project]
name = "coordsystems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Heliton Martins", email = "helitonmrf@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
    "plum-dispatch>=2.5.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
