# publish.yml

name: "Publish to PyPI"

on:
  release:
    types: ["published"]

jobs:
  run:
    name: "Build and publish release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish --token ${{ secrets.UV_PUBLISH_TOKEN }}
